version: 0.2.{build}-alpha
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Debug
platform: x86
install:
- cmd: >-
    git submodule update --init --recursive

    SET PATH=C:\projects\2dxngine\libs\opengl32;%PATH%
build:
  project: 2DXngine.sln
  verbosity: normal
test_script:
- ps: 2DXngine.Test\Debug\2DXngine.Test.exe --gtest_output=xml:2DXngine.Test.xml --gtest_filter=-SimpleCsvFile.*:ShaderProgramTestFixture.*:ShaderTestFixture.*:FontComponentTestFixute.*:RenderTargetTestFixture.*
on_finish:
- ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\2DXngine.Test.xml))