#include "TestComponents.h"

DEFINE_TYPE_INFO_VARIANTS(PlayerControllerComponentTest)
DEFINE_TYPE_INFO_VARIANTS(PlayerDrawableComponentTest)
DEFINE_TYPE_INFO_VARIANTS(SwordControllerComponentTest)
DEFINE_TYPE_INFO_VARIANTS(SwordDrawableComponentTest)
