#include "TestTypesHierarhy.h"

DEFINE_TYPE_INFO_VARIANTS(BaseType);
DEFINE_TYPE_INFO_VARIANTS(TestType1);
DEFINE_TYPE_INFO_VARIANTS(TestType2);
DEFINE_TYPE_INFO_VARIANTS(TestType3);
DEFINE_TYPE_INFO_VARIANTS(TestType4);